export const api = {
  dummyAPI: "users",
  userSignupWithEmail: "signUp",
  emailVerify: "verifyUser",
  userSignupWithMobile: "phoneSignUp",
  mobileVerify: "verifyPhone",
  loginCheack: "auth/loginCheack",
  loginCheackWithOtp: "auth/phoneLogin",
  loginCheackWithEmail: "auth/login",
  forgetPassword: "reset-password",
  verifyOtp: "verify-otp",
  resetPassword: "new-password-updated",
  socialLogin: "socialLogin",
  userDetails: "user-details",
  editProfile: "edit-profile",
  emailChangeStatus: "email-change-status",
  changePassword: "change-password",
  getHomeContent: "get-home-content",
  resendOtp: "resend_otp",
  getSearchProductResult:"get-search-product-result",
  getSearchProductCategory:"get-search-product-category",
  categoryList:"category-list",
  subcategoryList:"subcategory-list",
  ProductDetailsAPI:"get-product-details",
  AddToCart:"add-to-cart",
  AddToCartTemp:"add-to-temp-cart", 
  AddToWishlist:"wishlists",
  getCount:"get-count",
  getCountTemp:"get-temp-count",
  cartList:"get-cart-list",
  cartListTemp:"get-temp-cart-list",
  RemoveFromCart:"remove-from-cart",
  RemoveFromCartTemp:"remove-from-temp-cart",
  MoveMaster:"move-to-master-cart",
  getWishlist:"get-wishlist",
  newArrival:"new-arrival",
  bestSellers:"best-sellers",
  coupanCode:"apply-coupon-gcard",
  coupanCodeBeforeLogin:"apply-coupon-gcard-before-login",
  removeFormCartQty:"remove-from-cart-qty",
  removeFormCartQtyTemp:"remove-from-temp-cart-qty",
};